# Generated by Django 3.1 on 2022-01-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticles',
            old_name='auth',
            new_name='author',
        ),
    ]
